name: ifive_hrms
description: "A new Flutter project."

publish_to: 'none'

version: 1.1.0+1
#version: 1.3.2+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  firebase_core: ^2.25.4
  flutter_screenutil: ^5.9.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.7
  http: ^1.2.0
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.2
  intl: ^0.18.1
  permission_handler: ^11.2.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  shared_preferences: ^2.2.2
  dartz: ^0.10.1
  flutter_svg: ^2.0.9
  dropdown_textfield: ^1.0.8
  rxdart: ^0.27.7
  shimmer: ^3.0.0
  logger: ^2.0.2+1
  lottie: ^3.0.0
  dotted_border: ^2.1.0
  image_cropper: ^5.0.1
  image_picker: ^1.0.7
  flutter_localization: ^0.2.0
  carousel_slider: ^4.2.1
  path_provider: ^2.1.2
  flutter_cached_pdfview: ^0.4.2
  camera: ^0.10.5+9
  image: ^4.1.7
  package_info_plus: ^5.0.1
  flutter_slidable: ^3.1.0
  syncfusion_flutter_calendar: ^25.1.35
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:
  
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/svg/
    - assets/lottie/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Black.ttf
    - family: Satisfy
      fonts:
        - asset: assets/fonts/Satisfy-Regular.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Thin.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-ExtraLight.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf  
