// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzAn09v_dDSCECkWPbtmHwEojdllQIZZY',
    appId: '1:296910658175:android:8a3f5da95399e28d6dfd4a',
    messagingSenderId: '296910658175',
    projectId: 'ifive-30f06',
    databaseURL: 'https://ifive-30f06.firebaseio.com',
    storageBucket: 'ifive-30f06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt0PEE0J1gO4VsyWdhPK09ajjGzo_BVL8',
    appId: '1:296910658175:ios:15e37776b60b23b86dfd4a',
    messagingSenderId: '296910658175',
    projectId: 'ifive-30f06',
    databaseURL: 'https://ifive-30f06.firebaseio.com',
    storageBucket: 'ifive-30f06.appspot.com',
    androidClientId: '296910658175-khfu1ed80tjo5nr1aafc950in7c19jt2.apps.googleusercontent.com',
    iosBundleId: 'com.ifive.ifiveHrms',
  );
}
